//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangEntityClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string deviceList { get; set; }
        public decimal totalMoney { get; set; }
        public int discount { get; set; }
        public decimal finalMoney { get; set; }
        public Nullable<int> amount { get; set; }
    }
}
