//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangEntityClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string detail { get; set; }
        public string catalog { get; set; }
        public string type { get; set; }
        public int amount { get; set; }
        public decimal price { get; set; }
    }
}
